kind: Deployment
apiVersion: apps/v1
metadata:
  name: sailfish-example-consumer
  labels:
    app: sailfish-example-consumer
    app.kubernetes.io/component: sailfish-example-consumer
    app.kubernetes.io/instance: sailfish-example-consumer
    app.kubernetes.io/name: sailfish-example-consumer
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: dotnet
spec:
  template:
    spec:
      containers:
        - name: sailfish-example-producer
          image: >-
            ofocp.azurecr.io/labs/cloud-producer:latest
          