bases:
  - ../../base

images:
  - name: consumer-job-image
    newName: ghcr.io/ortec-finance/kedaconsumerjob
    newTag: latest
  - name: producer-image
    newName: ghcr.io/ortec-finance/kedaproducer
    newTag: latest

patchesJson6902:
- target:
    version: v1
    kind: Route
    name: sailfish-example-producer
  # Replace 'value' with your URL
  patch: |-
    - op: replace
      path: /spec/host
      value: sailfish-example-producer-hpc-sandbox.apps.ocp.ortec-finance.com
- target:
    version: v1
    kind: Deployment
    name: sailfish-example-producer
  # Replace 'value' with your URL
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local
- target:
    version: v1beta1
    kind: ActiveMQArtemis
    group: broker.amq.io
    name: sailfish-broker
  patch: |-
    - op: replace
      path: /spec/deploymentPlan/storage/storageClassName
      value: managed-premium
- target:
    version: v1alpha1
    kind: KedaController
    group: keda.sh
    name: keda
  patch: |-
    - op: replace
      path: /spec/watchNamespace
      value: hpc-sandbox      
- target:
    version: v1alpha1
    kind: ScaledJob
    group: keda.sh
    name: consumer-job
  patch: |-
    - op: replace
      path: /spec/jobTargetRef/template/spec/containers/0/env/4/value
      value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local 
- target:
    version: v1alpha1
    kind: ScaledJob
    group: keda.sh
    name: consumer-job
  patch: |-
    - op: replace
      path: /spec/triggers/0/metadata/managementEndpoint
      value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local:8161           