apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: consumer-job
  labels:
  app: sailfish-example-consumer
  app.kubernetes.io/component: sailfish-example-consumer
  app.kubernetes.io/instance: sailfish-example-consumer
  app.kubernetes.io/name: sailfish-example-consumer
  app.kubernetes.io/part-of: sample-sailfish-app
  app.openshift.io/runtime: dotnet
spec:
  jobTargetRef:
    ttlSecondsAfterFinished: 100 # completed or failed jobs will be removed after 100 seconds note that it successful an failed JobsHistoryLimit also afect kept jobs
    template:
      spec:
        nodeSelector:   
          ortec-finance/application: glass 
        tolerations:  
          - effect: NoSchedule
            key: ortec-finance
            value: glass-application
        containers:
        - name: consumer-job
          image: >-
            consumer-job-image
          imagePullPolicy: Always
          env:
            - name: ADDRESS
              value: sailfishWork
            - name: TIMEOUT
              value: '30'
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: sailfish-broker-credentials-secret
                  key: AMQ_USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sailfish-broker-credentials-secret
                  key: AMQ_PASSWORD
            - name: HOST
              value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local 
            - name: PORT
              value: '5672'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "250M"
              cpu: "750m"
            limits:
              memory: "1000M"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File          
        restartPolicy: Never
    backoffLimit: 4
    parallelism: 1   
  pollingInterval: 10 
  minReplicaCount: 0            
  maxReplicaCount: 20             # Optional. Default: 100
  successfulJobsHistoryLimit: 1   # Optional. Default: 100. How many completed jobs should be kept.
  failedJobsHistoryLimit: 5       # Optional. Default: 100. How many failed jobs should be kept.
  triggers:
    - authenticationRef:
        name: trigger-auth-sailfish
      metadata:
        brokerAddress: sailfishWork
        brokerName: amq-broker
        managementEndpoint: 'sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local:8161' # overwritten in kustomize overlay
        password: ARTEMIS_PASSWORD
        queueLength: '1'
        queueName: sailfishWork
        username: ARTEMIS_USER
      type: artemis-queue