bases:
  - ../../base

images:
  - name: consumer-image
    newName: ghcr.io/ortec-finance/kedaconsumer
    newTag: latest
  - name: producer-image
    newName: ghcr.io/ortec-finance/kedaproducer
    newTag: latest

patchesJson6902:
- target:
    version: v1
    kind: Deployment
    name: sailfish-example-consumer
  # Replace 'value' with your URL  
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/3/value
      value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local
- target:
    version: v1alpha1
    kind: ScaledObject
    name: keda-sailfish-consumer-scaled-object
  # Replace 'value' with your URL
  patch: |-
    - op: replace
      path: /spec/triggers/0/metadata/managementEndpoint
      value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local:8161
- target:
    version: v1
    kind: Route
    name: sailfish-example-producer
  # Replace 'value' with your URL
  patch: |-
    - op: replace
      path: /spec/host
      value: sailfish-example-producer-hpc-sandbox.apps.rosa-ocp.mxoj.p1.openshiftapps.com
- target:
    version: v1
    kind: Deployment
    name: sailfish-example-producer
  # Replace 'value' with your URL
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: sailfish-broker-hdls-svc.hpc-sandbox.svc.cluster.local
- target:
    version: v1beta1
    kind: ActiveMQArtemis
    group: broker.amq.io
    name: sailfish-broker
  patch: |-
    - op: replace
      path: /spec/deploymentPlan/storage/storageClassName
      value: gp2            